# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gbs3api.models.additional_dto import AdditionalDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AdditionalGroupDto(BaseModel):
    """
    AdditionalGroupDto
    """ # noqa: E501
    group_id: Optional[StrictInt] = Field(default=None, alias="groupId")
    name: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    category: Optional[StrictStr] = None
    sort_index: Optional[StrictInt] = Field(default=None, alias="sortIndex")
    path: Optional[StrictStr] = None
    show_in_report: Optional[StrictStr] = Field(default=None, alias="showInReport")
    additionals: Optional[List[AdditionalDto]] = None
    child_groups: Optional[List[AdditionalGroupDto]] = Field(default=None, alias="childGroups")
    __properties: ClassVar[List[str]] = ["groupId", "name", "label", "category", "sortIndex", "path", "showInReport", "additionals", "childGroups"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdditionalGroupDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in additionals (list)
        _items = []
        if self.additionals:
            for _item_additionals in self.additionals:
                if _item_additionals:
                    _items.append(_item_additionals.to_dict())
            _dict['additionals'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in child_groups (list)
        _items = []
        if self.child_groups:
            for _item_child_groups in self.child_groups:
                if _item_child_groups:
                    _items.append(_item_child_groups.to_dict())
            _dict['childGroups'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdditionalGroupDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "groupId": obj.get("groupId"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "category": obj.get("category"),
            "sortIndex": obj.get("sortIndex"),
            "path": obj.get("path"),
            "showInReport": obj.get("showInReport"),
            "additionals": [AdditionalDto.from_dict(_item) for _item in obj["additionals"]] if obj.get("additionals") is not None else None,
            "childGroups": [AdditionalGroupDto.from_dict(_item) for _item in obj["childGroups"]] if obj.get("childGroups") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
AdditionalGroupDto.model_rebuild(raise_errors=False)

