# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BomDto(BaseModel):
    """
    BomDto
    """ # noqa: E501
    bom_id: Optional[StrictInt] = Field(default=None, alias="bomId")
    material: Optional[StrictStr] = None
    material_description: Optional[StrictStr] = Field(default=None, alias="materialDescription")
    plant: Optional[StrictStr] = None
    item_number: Optional[StrictStr] = Field(default=None, alias="itemNumber")
    item_category: Optional[StrictStr] = Field(default=None, alias="itemCategory")
    source_system_key: Optional[StrictStr] = Field(default=None, alias="sourceSystemKey")
    bom_elements: Optional[List[BomDto]] = Field(default=None, alias="bomElements")
    __properties: ClassVar[List[str]] = ["bomId", "material", "materialDescription", "plant", "itemNumber", "itemCategory", "sourceSystemKey", "bomElements"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BomDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bom_elements (list)
        _items = []
        if self.bom_elements:
            for _item_bom_elements in self.bom_elements:
                if _item_bom_elements:
                    _items.append(_item_bom_elements.to_dict())
            _dict['bomElements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BomDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bomId": obj.get("bomId"),
            "material": obj.get("material"),
            "materialDescription": obj.get("materialDescription"),
            "plant": obj.get("plant"),
            "itemNumber": obj.get("itemNumber"),
            "itemCategory": obj.get("itemCategory"),
            "sourceSystemKey": obj.get("sourceSystemKey"),
            "bomElements": [BomDto.from_dict(_item) for _item in obj["bomElements"]] if obj.get("bomElements") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
BomDto.model_rebuild(raise_errors=False)

