# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gbs3api.models.additional_group import AdditionalGroup
from gbs3api.models.additional_information_type import AdditionalInformationType
from gbs3api.models.component_test_group_type import ComponentTestGroupType
from gbs3api.models.diagram_information_type import DiagramInformationType
from gbs3api.models.document_information_type import DocumentInformationType
from gbs3api.models.movie_information_type import MovieInformationType
from gbs3api.models.parts_group import PartsGroup
from gbs3api.models.photo_information_type import PhotoInformationType
from gbs3api.models.raw_information_type import RawInformationType
from gbs3api.models.report_information_type import ReportInformationType
from gbs3api.models.sample_data_type import SampleDataType
from gbs3api.models.static_information_type import StaticInformationType
from gbs3api.models.test_fixture import TestFixture
from gbs3api.models.test_object_type import TestObjectType
from gbs3api.models.test_step_layout import TestStepLayout
from gbs3api.models.work_instruction import WorkInstruction
from typing import Optional, Set
from typing_extensions import Self

class GeneralInformationType(BaseModel):
    """
    GeneralInformationType
    """ # noqa: E501
    path: Optional[StrictStr] = None
    test_number: StrictStr = Field(alias="testNumber")
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    is_test_step: Optional[StrictBool] = Field(default=None, alias="isTestStep")
    version: Optional[StrictInt] = None
    test_category: Optional[StrictStr] = Field(default=None, alias="testCategory")
    name: Optional[StrictStr] = None
    test_step_layout: Optional[TestStepLayout] = Field(default=None, alias="testStepLayout")
    samples: Optional[StrictStr] = None
    laboratory_name: StrictStr = Field(alias="laboratoryName")
    laboratory_contact_name: Optional[StrictStr] = Field(default=None, alias="laboratoryContactName")
    laboratory_contact_phone: Optional[StrictStr] = Field(default=None, alias="laboratoryContactPhone")
    laboratory_contact_fax: Optional[StrictStr] = Field(default=None, alias="laboratoryContactFax")
    laboratory_contact_email: Optional[StrictStr] = Field(default=None, alias="laboratoryContactEmail")
    laboratory_test_ref_number: StrictStr = Field(alias="laboratoryTestRefNumber")
    requestor_name: Optional[StrictStr] = Field(default=None, alias="requestorName")
    requestor_phone: Optional[StrictStr] = Field(default=None, alias="requestorPhone")
    currently_logged_user: Optional[StrictStr] = Field(default=None, alias="currentlyLoggedUser")
    proxy_contact_name: Optional[StrictStr] = Field(default=None, alias="proxyContactName")
    proxy_contact_phone: Optional[StrictStr] = Field(default=None, alias="proxyContactPhone")
    responsible_location: Optional[StrictStr] = Field(default=None, alias="responsibleLocation")
    responsible_location_address: Optional[StrictStr] = Field(default=None, alias="responsibleLocationAddress")
    proxy_contact_fax: Optional[StrictStr] = Field(default=None, alias="proxyContactFax")
    proxy_contact_email: Optional[StrictStr] = Field(default=None, alias="proxyContactEmail")
    customer_name: StrictStr = Field(alias="customerName")
    customer_test_ref_number: StrictStr = Field(alias="customerTestRefNumber")
    customer_project_ref_number: Optional[StrictStr] = Field(default=None, alias="customerProjectRefNumber")
    customer_order_number: Optional[StrictStr] = Field(default=None, alias="customerOrderNumber")
    customer_cost_unit: Optional[StrictStr] = Field(default=None, alias="customerCostUnit")
    customer_test_engineer_name: Optional[StrictStr] = Field(default=None, alias="customerTestEngineerName")
    customer_test_engineer_phone: Optional[StrictStr] = Field(default=None, alias="customerTestEngineerPhone")
    customer_test_engineer_fax: Optional[StrictStr] = Field(default=None, alias="customerTestEngineerFax")
    customer_test_engineer_email: Optional[StrictStr] = Field(default=None, alias="customerTestEngineerEmail")
    title: StrictStr
    type_of_the_test: StrictStr = Field(alias="typeOfTheTest")
    subtype_of_the_test: StrictStr = Field(alias="subtypeOfTheTest")
    template_name: StrictStr = Field(alias="templateName")
    regulation: Optional[StrictStr] = None
    reference_temperature: Optional[StrictStr] = Field(default=None, alias="referenceTemperature")
    relative_air_humidity: Optional[StrictStr] = Field(default=None, alias="relativeAirHumidity")
    date_of_the_test: datetime = Field(alias="dateOfTheTest")
    estimated_start: Optional[datetime] = Field(default=None, alias="estimatedStart")
    estimated_end: Optional[datetime] = Field(default=None, alias="estimatedEnd")
    actual_end: Optional[datetime] = Field(default=None, alias="actualEnd")
    order_date: Optional[datetime] = Field(default=None, alias="orderDate")
    deadline_lab: Optional[datetime] = Field(default=None, alias="deadlineLab")
    instrumentation_standard: Optional[StrictStr] = Field(default=None, alias="instrumentationStandard")
    test_bench: Optional[StrictStr] = Field(default=None, alias="testBench")
    intention: Optional[StrictStr] = None
    customer_visit: Optional[StrictBool] = Field(default=None, alias="customerVisit")
    customer_visit_telephone_number: Optional[StrictStr] = Field(default=None, alias="customerVisitTelephoneNumber")
    remark: Optional[StrictStr] = None
    location: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    execution_status: Optional[StrictStr] = Field(default=None, alias="executionStatus")
    work_time: Optional[StrictInt] = Field(default=None, alias="workTime")
    work_time_start: Optional[datetime] = Field(default=None, alias="workTimeStart")
    skill_id_list: Optional[StrictStr] = Field(default=None, alias="skillIdList")
    work_instruction: Optional[List[WorkInstruction]] = Field(default=None, alias="workInstruction")
    test_fixture: Optional[List[TestFixture]] = Field(default=None, alias="testFixture")
    sample: Optional[List[SampleDataType]] = None
    sub_tests: Optional[List[TestDataType]] = Field(default=None, alias="subTests")
    test_object: Optional[List[TestObjectType]] = Field(default=None, alias="testObject")
    additional_group: Optional[List[AdditionalGroup]] = Field(default=None, alias="additionalGroup")
    source: Optional[StrictStr] = None
    diagram: Optional[DiagramInformationType] = None
    document: Optional[DocumentInformationType] = None
    movie: Optional[MovieInformationType] = None
    photo: Optional[PhotoInformationType] = None
    raw: Optional[RawInformationType] = None
    report: Optional[ReportInformationType] = None
    statics: Optional[StaticInformationType] = None
    additional: Optional[AdditionalInformationType] = None
    component_test_group: Optional[ComponentTestGroupType] = Field(default=None, alias="componentTestGroup")
    parts_group: Optional[List[PartsGroup]] = Field(default=None, alias="partsGroup")
    vpn_r_pos: Optional[StrictStr] = Field(default=None, alias="vpnRPos")
    element_name: Optional[StrictStr] = Field(default=None, alias="elementName")
    sapnetplan: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["path", "testNumber", "isActive", "isTestStep", "version", "testCategory", "name", "testStepLayout", "samples", "laboratoryName", "laboratoryContactName", "laboratoryContactPhone", "laboratoryContactFax", "laboratoryContactEmail", "laboratoryTestRefNumber", "requestorName", "requestorPhone", "currentlyLoggedUser", "proxyContactName", "proxyContactPhone", "responsibleLocation", "responsibleLocationAddress", "proxyContactFax", "proxyContactEmail", "customerName", "customerTestRefNumber", "customerProjectRefNumber", "customerOrderNumber", "customerCostUnit", "customerTestEngineerName", "customerTestEngineerPhone", "customerTestEngineerFax", "customerTestEngineerEmail", "title", "typeOfTheTest", "subtypeOfTheTest", "templateName", "regulation", "referenceTemperature", "relativeAirHumidity", "dateOfTheTest", "estimatedStart", "estimatedEnd", "actualEnd", "orderDate", "deadlineLab", "instrumentationStandard", "testBench", "intention", "customerVisit", "customerVisitTelephoneNumber", "remark", "location", "status", "executionStatus", "workTime", "workTimeStart", "skillIdList", "workInstruction", "testFixture", "sample", "subTests", "testObject", "additionalGroup", "source", "diagram", "document", "movie", "photo", "raw", "report", "statics", "additional", "componentTestGroup", "partsGroup", "vpnRPos", "elementName", "sapnetplan"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DEF', 'VAL', 'ORD', 'PRE', 'EXE', 'POS', 'ANA', 'AOR', 'ARC', 'CAN', 'FAI', 'FIN']):
            raise ValueError("must be one of enum values ('DEF', 'VAL', 'ORD', 'PRE', 'EXE', 'POS', 'ANA', 'AOR', 'ARC', 'CAN', 'FAI', 'FIN')")
        return value

    @field_validator('execution_status')
    def execution_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['QUE', 'PRO', 'FIN', 'ABO']):
            raise ValueError("must be one of enum values ('QUE', 'PRO', 'FIN', 'ABO')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneralInformationType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test_step_layout
        if self.test_step_layout:
            _dict['testStepLayout'] = self.test_step_layout.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in work_instruction (list)
        _items = []
        if self.work_instruction:
            for _item_work_instruction in self.work_instruction:
                if _item_work_instruction:
                    _items.append(_item_work_instruction.to_dict())
            _dict['workInstruction'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_fixture (list)
        _items = []
        if self.test_fixture:
            for _item_test_fixture in self.test_fixture:
                if _item_test_fixture:
                    _items.append(_item_test_fixture.to_dict())
            _dict['testFixture'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sample (list)
        _items = []
        if self.sample:
            for _item_sample in self.sample:
                if _item_sample:
                    _items.append(_item_sample.to_dict())
            _dict['sample'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_tests (list)
        _items = []
        if self.sub_tests:
            for _item_sub_tests in self.sub_tests:
                if _item_sub_tests:
                    _items.append(_item_sub_tests.to_dict())
            _dict['subTests'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_object (list)
        _items = []
        if self.test_object:
            for _item_test_object in self.test_object:
                if _item_test_object:
                    _items.append(_item_test_object.to_dict())
            _dict['testObject'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in additional_group (list)
        _items = []
        if self.additional_group:
            for _item_additional_group in self.additional_group:
                if _item_additional_group:
                    _items.append(_item_additional_group.to_dict())
            _dict['additionalGroup'] = _items
        # override the default output from pydantic by calling `to_dict()` of diagram
        if self.diagram:
            _dict['diagram'] = self.diagram.to_dict()
        # override the default output from pydantic by calling `to_dict()` of document
        if self.document:
            _dict['document'] = self.document.to_dict()
        # override the default output from pydantic by calling `to_dict()` of movie
        if self.movie:
            _dict['movie'] = self.movie.to_dict()
        # override the default output from pydantic by calling `to_dict()` of photo
        if self.photo:
            _dict['photo'] = self.photo.to_dict()
        # override the default output from pydantic by calling `to_dict()` of raw
        if self.raw:
            _dict['raw'] = self.raw.to_dict()
        # override the default output from pydantic by calling `to_dict()` of report
        if self.report:
            _dict['report'] = self.report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of statics
        if self.statics:
            _dict['statics'] = self.statics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of additional
        if self.additional:
            _dict['additional'] = self.additional.to_dict()
        # override the default output from pydantic by calling `to_dict()` of component_test_group
        if self.component_test_group:
            _dict['componentTestGroup'] = self.component_test_group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in parts_group (list)
        _items = []
        if self.parts_group:
            for _item_parts_group in self.parts_group:
                if _item_parts_group:
                    _items.append(_item_parts_group.to_dict())
            _dict['partsGroup'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneralInformationType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "testNumber": obj.get("testNumber"),
            "isActive": obj.get("isActive"),
            "isTestStep": obj.get("isTestStep"),
            "version": obj.get("version"),
            "testCategory": obj.get("testCategory"),
            "name": obj.get("name"),
            "testStepLayout": TestStepLayout.from_dict(obj["testStepLayout"]) if obj.get("testStepLayout") is not None else None,
            "samples": obj.get("samples"),
            "laboratoryName": obj.get("laboratoryName"),
            "laboratoryContactName": obj.get("laboratoryContactName"),
            "laboratoryContactPhone": obj.get("laboratoryContactPhone"),
            "laboratoryContactFax": obj.get("laboratoryContactFax"),
            "laboratoryContactEmail": obj.get("laboratoryContactEmail"),
            "laboratoryTestRefNumber": obj.get("laboratoryTestRefNumber"),
            "requestorName": obj.get("requestorName"),
            "requestorPhone": obj.get("requestorPhone"),
            "currentlyLoggedUser": obj.get("currentlyLoggedUser"),
            "proxyContactName": obj.get("proxyContactName"),
            "proxyContactPhone": obj.get("proxyContactPhone"),
            "responsibleLocation": obj.get("responsibleLocation"),
            "responsibleLocationAddress": obj.get("responsibleLocationAddress"),
            "proxyContactFax": obj.get("proxyContactFax"),
            "proxyContactEmail": obj.get("proxyContactEmail"),
            "customerName": obj.get("customerName"),
            "customerTestRefNumber": obj.get("customerTestRefNumber"),
            "customerProjectRefNumber": obj.get("customerProjectRefNumber"),
            "customerOrderNumber": obj.get("customerOrderNumber"),
            "customerCostUnit": obj.get("customerCostUnit"),
            "customerTestEngineerName": obj.get("customerTestEngineerName"),
            "customerTestEngineerPhone": obj.get("customerTestEngineerPhone"),
            "customerTestEngineerFax": obj.get("customerTestEngineerFax"),
            "customerTestEngineerEmail": obj.get("customerTestEngineerEmail"),
            "title": obj.get("title"),
            "typeOfTheTest": obj.get("typeOfTheTest"),
            "subtypeOfTheTest": obj.get("subtypeOfTheTest"),
            "templateName": obj.get("templateName"),
            "regulation": obj.get("regulation"),
            "referenceTemperature": obj.get("referenceTemperature"),
            "relativeAirHumidity": obj.get("relativeAirHumidity"),
            "dateOfTheTest": obj.get("dateOfTheTest"),
            "estimatedStart": obj.get("estimatedStart"),
            "estimatedEnd": obj.get("estimatedEnd"),
            "actualEnd": obj.get("actualEnd"),
            "orderDate": obj.get("orderDate"),
            "deadlineLab": obj.get("deadlineLab"),
            "instrumentationStandard": obj.get("instrumentationStandard"),
            "testBench": obj.get("testBench"),
            "intention": obj.get("intention"),
            "customerVisit": obj.get("customerVisit"),
            "customerVisitTelephoneNumber": obj.get("customerVisitTelephoneNumber"),
            "remark": obj.get("remark"),
            "location": obj.get("location"),
            "status": obj.get("status"),
            "executionStatus": obj.get("executionStatus"),
            "workTime": obj.get("workTime"),
            "workTimeStart": obj.get("workTimeStart"),
            "skillIdList": obj.get("skillIdList"),
            "workInstruction": [WorkInstruction.from_dict(_item) for _item in obj["workInstruction"]] if obj.get("workInstruction") is not None else None,
            "testFixture": [TestFixture.from_dict(_item) for _item in obj["testFixture"]] if obj.get("testFixture") is not None else None,
            "sample": [SampleDataType.from_dict(_item) for _item in obj["sample"]] if obj.get("sample") is not None else None,
            "subTests": [TestDataType.from_dict(_item) for _item in obj["subTests"]] if obj.get("subTests") is not None else None,
            "testObject": [TestObjectType.from_dict(_item) for _item in obj["testObject"]] if obj.get("testObject") is not None else None,
            "additionalGroup": [AdditionalGroup.from_dict(_item) for _item in obj["additionalGroup"]] if obj.get("additionalGroup") is not None else None,
            "source": obj.get("source"),
            "diagram": DiagramInformationType.from_dict(obj["diagram"]) if obj.get("diagram") is not None else None,
            "document": DocumentInformationType.from_dict(obj["document"]) if obj.get("document") is not None else None,
            "movie": MovieInformationType.from_dict(obj["movie"]) if obj.get("movie") is not None else None,
            "photo": PhotoInformationType.from_dict(obj["photo"]) if obj.get("photo") is not None else None,
            "raw": RawInformationType.from_dict(obj["raw"]) if obj.get("raw") is not None else None,
            "report": ReportInformationType.from_dict(obj["report"]) if obj.get("report") is not None else None,
            "statics": StaticInformationType.from_dict(obj["statics"]) if obj.get("statics") is not None else None,
            "additional": AdditionalInformationType.from_dict(obj["additional"]) if obj.get("additional") is not None else None,
            "componentTestGroup": ComponentTestGroupType.from_dict(obj["componentTestGroup"]) if obj.get("componentTestGroup") is not None else None,
            "partsGroup": [PartsGroup.from_dict(_item) for _item in obj["partsGroup"]] if obj.get("partsGroup") is not None else None,
            "vpnRPos": obj.get("vpnRPos"),
            "elementName": obj.get("elementName"),
            "sapnetplan": obj.get("sapnetplan")
        })
        return _obj

from gbs3api.models.test_data_type import TestDataType
# TODO: Rewrite to not use raise_errors
GeneralInformationType.model_rebuild(raise_errors=False)

