# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gbs3api.models.additional_group import AdditionalGroup
from gbs3api.models.sample_element_data_type import SampleElementDataType
from gbs3api.models.sample_info_data_type import SampleInfoDataType
from gbs3api.models.sample_type_data_type import SampleTypeDataType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SampleDataType(BaseModel):
    """
    SampleDataType
    """ # noqa: E501
    path: Optional[StrictStr] = None
    position_number: StrictStr = Field(alias="positionNumber")
    sample_id: StrictStr = Field(alias="sampleId")
    customer_part_number: Optional[StrictStr] = Field(default=None, alias="customerPartNumber")
    amount: Optional[StrictInt] = None
    remark: Optional[StrictStr] = None
    software: Optional[StrictStr] = None
    version: Optional[StrictStr] = None
    unloading_place: Optional[StrictStr] = Field(default=None, alias="unloadingPlace")
    part_name: Optional[StrictStr] = Field(default=None, alias="partName")
    ebom: Optional[StrictStr] = None
    manufacturer: Optional[StrictStr] = None
    manufacturer_number: Optional[StrictStr] = Field(default=None, alias="manufacturerNumber")
    manufacturer_number_version: Optional[StrictStr] = Field(default=None, alias="manufacturerNumberVersion")
    customer_version: Optional[StrictStr] = Field(default=None, alias="customerVersion")
    warehouse_id: Optional[StrictStr] = Field(default=None, alias="warehouseId")
    source_id: Optional[StrictStr] = Field(default=None, alias="sourceId")
    sample_info: Optional[SampleInfoDataType] = Field(default=None, alias="sampleInfo")
    sample_type: Optional[SampleTypeDataType] = Field(default=None, alias="sampleType")
    location: Optional[StrictStr] = None
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    prototype_sort_index: Optional[StrictInt] = Field(default=None, alias="prototypeSortIndex")
    sample_elements: Optional[List[SampleElementDataType]] = Field(default=None, alias="sampleElements")
    additional_group: Optional[List[AdditionalGroup]] = Field(default=None, alias="additionalGroup")
    element_name: Optional[StrictStr] = Field(default=None, alias="elementName")
    pbsfin_good_id: Optional[StrictStr] = Field(default=None, alias="pbsfinGoodId")
    __properties: ClassVar[List[str]] = ["path", "positionNumber", "sampleId", "customerPartNumber", "amount", "remark", "software", "version", "unloadingPlace", "partName", "ebom", "manufacturer", "manufacturerNumber", "manufacturerNumberVersion", "customerVersion", "warehouseId", "sourceId", "sampleInfo", "sampleType", "location", "isDeleted", "prototypeSortIndex", "sampleElements", "additionalGroup", "elementName", "pbsfinGoodId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SampleDataType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sample_info
        if self.sample_info:
            _dict['sampleInfo'] = self.sample_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sample_type
        if self.sample_type:
            _dict['sampleType'] = self.sample_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sample_elements (list)
        _items = []
        if self.sample_elements:
            for _item_sample_elements in self.sample_elements:
                if _item_sample_elements:
                    _items.append(_item_sample_elements.to_dict())
            _dict['sampleElements'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in additional_group (list)
        _items = []
        if self.additional_group:
            for _item_additional_group in self.additional_group:
                if _item_additional_group:
                    _items.append(_item_additional_group.to_dict())
            _dict['additionalGroup'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SampleDataType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "positionNumber": obj.get("positionNumber"),
            "sampleId": obj.get("sampleId"),
            "customerPartNumber": obj.get("customerPartNumber"),
            "amount": obj.get("amount"),
            "remark": obj.get("remark"),
            "software": obj.get("software"),
            "version": obj.get("version"),
            "unloadingPlace": obj.get("unloadingPlace"),
            "partName": obj.get("partName"),
            "ebom": obj.get("ebom"),
            "manufacturer": obj.get("manufacturer"),
            "manufacturerNumber": obj.get("manufacturerNumber"),
            "manufacturerNumberVersion": obj.get("manufacturerNumberVersion"),
            "customerVersion": obj.get("customerVersion"),
            "warehouseId": obj.get("warehouseId"),
            "sourceId": obj.get("sourceId"),
            "sampleInfo": SampleInfoDataType.from_dict(obj["sampleInfo"]) if obj.get("sampleInfo") is not None else None,
            "sampleType": SampleTypeDataType.from_dict(obj["sampleType"]) if obj.get("sampleType") is not None else None,
            "location": obj.get("location"),
            "isDeleted": obj.get("isDeleted"),
            "prototypeSortIndex": obj.get("prototypeSortIndex"),
            "sampleElements": [SampleElementDataType.from_dict(_item) for _item in obj["sampleElements"]] if obj.get("sampleElements") is not None else None,
            "additionalGroup": [AdditionalGroup.from_dict(_item) for _item in obj["additionalGroup"]] if obj.get("additionalGroup") is not None else None,
            "elementName": obj.get("elementName"),
            "pbsfinGoodId": obj.get("pbsfinGoodId")
        })
        return _obj


