# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TestFixtureStatusComment(BaseModel):
    """
    TestFixtureStatusComment
    """ # noqa: E501
    path: Optional[StrictStr] = None
    comment_date: StrictStr = Field(alias="commentDate")
    user: StrictStr
    comment: StrictStr
    old_status: StrictStr = Field(alias="oldStatus")
    new_status: StrictStr = Field(alias="newStatus")
    element_name: Optional[StrictStr] = Field(default=None, alias="elementName")
    __properties: ClassVar[List[str]] = ["path", "commentDate", "user", "comment", "oldStatus", "newStatus", "elementName"]

    @field_validator('old_status')
    def old_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['QUARANTINE', 'OPERATION', 'TEST']):
            raise ValueError("must be one of enum values ('QUARANTINE', 'OPERATION', 'TEST')")
        return value

    @field_validator('new_status')
    def new_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['QUARANTINE', 'OPERATION', 'TEST']):
            raise ValueError("must be one of enum values ('QUARANTINE', 'OPERATION', 'TEST')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestFixtureStatusComment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestFixtureStatusComment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "commentDate": obj.get("commentDate"),
            "user": obj.get("user"),
            "comment": obj.get("comment"),
            "oldStatus": obj.get("oldStatus"),
            "newStatus": obj.get("newStatus"),
            "elementName": obj.get("elementName")
        })
        return _obj


