# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gbs3api.models.additional_group import AdditionalGroup
from typing import Optional, Set
from typing_extensions import Self

class TestFixtureType(BaseModel):
    """
    TestFixtureType
    """ # noqa: E501
    path: Optional[StrictStr] = None
    name: StrictStr
    category: StrictStr
    resource_type_scheduling: Optional[StrictStr] = Field(default=None, alias="resourceTypeScheduling")
    resource_type_scheduling_id: Optional[StrictStr] = Field(default=None, alias="resourceTypeSchedulingId")
    additional_group: Optional[List[AdditionalGroup]] = Field(default=None, alias="additionalGroup")
    element_name: Optional[StrictStr] = Field(default=None, alias="elementName")
    __properties: ClassVar[List[str]] = ["path", "name", "category", "resourceTypeScheduling", "resourceTypeSchedulingId", "additionalGroup", "elementName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestFixtureType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in additional_group (list)
        _items = []
        if self.additional_group:
            for _item_additional_group in self.additional_group:
                if _item_additional_group:
                    _items.append(_item_additional_group.to_dict())
            _dict['additionalGroup'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestFixtureType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "name": obj.get("name"),
            "category": obj.get("category"),
            "resourceTypeScheduling": obj.get("resourceTypeScheduling"),
            "resourceTypeSchedulingId": obj.get("resourceTypeSchedulingId"),
            "additionalGroup": [AdditionalGroup.from_dict(_item) for _item in obj["additionalGroup"]] if obj.get("additionalGroup") is not None else None,
            "elementName": obj.get("elementName")
        })
        return _obj


