# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gbs3api.models.test_sequence_dto import TestSequenceDto
from typing import Optional, Set
from typing_extensions import Self

class TestSeriesDto(BaseModel):
    """
    TestSeriesDto
    """ # noqa: E501
    sequence_dtos: Optional[List[TestSequenceDto]] = Field(default=None, alias="sequenceDtos")
    series_id: Optional[StrictInt] = Field(default=None, alias="seriesId")
    series_number: Optional[StrictStr] = Field(default=None, alias="seriesNumber")
    development_phase: Optional[StrictStr] = Field(default=None, alias="developmentPhase")
    number_of_tests: Optional[StrictInt] = Field(default=None, alias="numberOfTests")
    estimated_start: Optional[datetime] = Field(default=None, alias="estimatedStart")
    estimated_end: Optional[datetime] = Field(default=None, alias="estimatedEnd")
    actual_start: Optional[datetime] = Field(default=None, alias="actualStart")
    actual_end: Optional[datetime] = Field(default=None, alias="actualEnd")
    parts_available: Optional[datetime] = Field(default=None, alias="partsAvailable")
    deadline_lab: Optional[datetime] = Field(default=None, alias="deadlineLab")
    creation_date: Optional[datetime] = Field(default=None, alias="creationDate")
    testtype: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    sap_netplan: Optional[StrictStr] = Field(default=None, alias="sapNetplan")
    lab_net_plan: Optional[StrictStr] = Field(default=None, alias="labNetPlan")
    remark: Optional[StrictStr] = None
    task: Optional[StrictStr] = None
    platform_code: Optional[StrictStr] = Field(default=None, alias="platformCode")
    market_code: Optional[StrictStr] = Field(default=None, alias="marketCode")
    producer: Optional[StrictStr] = None
    kba_category: Optional[StrictStr] = Field(default=None, alias="kbaCategory")
    tests_numbers_scope: Optional[StrictStr] = Field(default=None, alias="testsNumbersScope")
    first_part: Optional[StrictStr] = Field(default=None, alias="firstPart")
    last_part: Optional[StrictStr] = Field(default=None, alias="lastPart")
    customer_name: Optional[StrictStr] = Field(default=None, alias="customerName")
    function_number: Optional[StrictStr] = Field(default=None, alias="functionNumber")
    wbs_element: Optional[StrictStr] = Field(default=None, alias="wbsElement")
    gbs_test_serie_link: Optional[StrictStr] = Field(default=None, alias="gbsTestSerieLink")
    responsible_location_address: Optional[StrictStr] = Field(default=None, alias="responsibleLocationAddress")
    project: Optional[StrictStr] = None
    sequences: Optional[List[TestSequenceDto]] = None
    __properties: ClassVar[List[str]] = ["sequenceDtos", "seriesId", "seriesNumber", "developmentPhase", "numberOfTests", "estimatedStart", "estimatedEnd", "actualStart", "actualEnd", "partsAvailable", "deadlineLab", "creationDate", "testtype", "status", "sapNetplan", "labNetPlan", "remark", "task", "platformCode", "marketCode", "producer", "kbaCategory", "testsNumbersScope", "firstPart", "lastPart", "customerName", "functionNumber", "wbsElement", "gbsTestSerieLink", "responsibleLocationAddress", "project", "sequences"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestSeriesDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sequence_dtos (list)
        _items = []
        if self.sequence_dtos:
            for _item_sequence_dtos in self.sequence_dtos:
                if _item_sequence_dtos:
                    _items.append(_item_sequence_dtos.to_dict())
            _dict['sequenceDtos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sequences (list)
        _items = []
        if self.sequences:
            for _item_sequences in self.sequences:
                if _item_sequences:
                    _items.append(_item_sequences.to_dict())
            _dict['sequences'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestSeriesDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sequenceDtos": [TestSequenceDto.from_dict(_item) for _item in obj["sequenceDtos"]] if obj.get("sequenceDtos") is not None else None,
            "seriesId": obj.get("seriesId"),
            "seriesNumber": obj.get("seriesNumber"),
            "developmentPhase": obj.get("developmentPhase"),
            "numberOfTests": obj.get("numberOfTests"),
            "estimatedStart": obj.get("estimatedStart"),
            "estimatedEnd": obj.get("estimatedEnd"),
            "actualStart": obj.get("actualStart"),
            "actualEnd": obj.get("actualEnd"),
            "partsAvailable": obj.get("partsAvailable"),
            "deadlineLab": obj.get("deadlineLab"),
            "creationDate": obj.get("creationDate"),
            "testtype": obj.get("testtype"),
            "status": obj.get("status"),
            "sapNetplan": obj.get("sapNetplan"),
            "labNetPlan": obj.get("labNetPlan"),
            "remark": obj.get("remark"),
            "task": obj.get("task"),
            "platformCode": obj.get("platformCode"),
            "marketCode": obj.get("marketCode"),
            "producer": obj.get("producer"),
            "kbaCategory": obj.get("kbaCategory"),
            "testsNumbersScope": obj.get("testsNumbersScope"),
            "firstPart": obj.get("firstPart"),
            "lastPart": obj.get("lastPart"),
            "customerName": obj.get("customerName"),
            "functionNumber": obj.get("functionNumber"),
            "wbsElement": obj.get("wbsElement"),
            "gbsTestSerieLink": obj.get("gbsTestSerieLink"),
            "responsibleLocationAddress": obj.get("responsibleLocationAddress"),
            "project": obj.get("project"),
            "sequences": [TestSequenceDto.from_dict(_item) for _item in obj["sequences"]] if obj.get("sequences") is not None else None
        })
        return _obj


