# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gbs3api.models.additional_group import AdditionalGroup
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestDataType(BaseModel):
    """
    TestDataType
    """ # noqa: E501
    path: Optional[StrictStr] = None
    instance: Optional[StrictStr] = None
    host: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    general_information: GeneralInformationType = Field(alias="generalInformation")
    additional_group: Optional[List[AdditionalGroup]] = Field(default=None, alias="additionalGroup")
    element_name: Optional[StrictStr] = Field(default=None, alias="elementName")
    __properties: ClassVar[List[str]] = ["path", "instance", "host", "source", "generalInformation", "additionalGroup", "elementName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestDataType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of general_information
        if self.general_information:
            _dict['generalInformation'] = self.general_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in additional_group (list)
        _items = []
        if self.additional_group:
            for _item_additional_group in self.additional_group:
                if _item_additional_group:
                    _items.append(_item_additional_group.to_dict())
            _dict['additionalGroup'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestDataType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "instance": obj.get("instance"),
            "host": obj.get("host"),
            "source": obj.get("source"),
            "generalInformation": GeneralInformationType.from_dict(obj["generalInformation"]) if obj.get("generalInformation") is not None else None,
            "additionalGroup": [AdditionalGroup.from_dict(_item) for _item in obj["additionalGroup"]] if obj.get("additionalGroup") is not None else None,
            "elementName": obj.get("elementName")
        })
        return _obj

from gbs3api.models.general_information_type import GeneralInformationType
# TODO: Rewrite to not use raise_errors
TestDataType.model_rebuild(raise_errors=False)

