# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TestFixtureRental(BaseModel):
    """
    TestFixtureRental
    """ # noqa: E501
    path: Optional[StrictStr] = None
    rental_date: datetime = Field(alias="rentalDate")
    return_date: Optional[datetime] = Field(default=None, alias="returnDate")
    target_date: Optional[datetime] = Field(default=None, alias="targetDate")
    contact_name: StrictStr = Field(alias="contactName")
    contact_phone: StrictStr = Field(alias="contactPhone")
    contact_fax: StrictStr = Field(alias="contactFax")
    contact_email: StrictStr = Field(alias="contactEmail")
    description: Optional[StrictStr] = None
    lender: StrictStr
    hour_period: Optional[StrictInt] = Field(default=None, alias="hourPeriod")
    day_period: Optional[StrictInt] = Field(default=None, alias="dayPeriod")
    month_period: Optional[StrictInt] = Field(default=None, alias="monthPeriod")
    indefinite_period: Optional[StrictBool] = Field(default=None, alias="indefinitePeriod")
    extend_loan_count: Optional[StrictInt] = Field(default=None, alias="extendLoanCount")
    element_name: Optional[StrictStr] = Field(default=None, alias="elementName")
    __properties: ClassVar[List[str]] = ["path", "rentalDate", "returnDate", "targetDate", "contactName", "contactPhone", "contactFax", "contactEmail", "description", "lender", "hourPeriod", "dayPeriod", "monthPeriod", "indefinitePeriod", "extendLoanCount", "elementName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestFixtureRental from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestFixtureRental from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "rentalDate": obj.get("rentalDate"),
            "returnDate": obj.get("returnDate"),
            "targetDate": obj.get("targetDate"),
            "contactName": obj.get("contactName"),
            "contactPhone": obj.get("contactPhone"),
            "contactFax": obj.get("contactFax"),
            "contactEmail": obj.get("contactEmail"),
            "description": obj.get("description"),
            "lender": obj.get("lender"),
            "hourPeriod": obj.get("hourPeriod"),
            "dayPeriod": obj.get("dayPeriod"),
            "monthPeriod": obj.get("monthPeriod"),
            "indefinitePeriod": obj.get("indefinitePeriod"),
            "extendLoanCount": obj.get("extendLoanCount"),
            "elementName": obj.get("elementName")
        })
        return _obj


