# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PreTestDto(BaseModel):
    """
    PreTestDto
    """ # noqa: E501
    driver_position: StrictInt = Field(alias="driverPosition")
    customer_test_ref_no: StrictStr = Field(alias="customerTestRefNo")
    laboratory_test_ref_no: StrictStr = Field(alias="laboratoryTestRefNo")
    date_of_test: date = Field(alias="dateOfTest")
    velocity_pulse: Union[StrictFloat, StrictInt] = Field(alias="velocityPulse")
    pulse_status: StrictStr = Field(alias="pulseStatus")
    impact_side: Optional[StrictStr] = Field(default=None, alias="impactSide")
    test_type: Optional[StrictStr] = Field(default=None, alias="testType")
    sub_test_type: Optional[StrictStr] = Field(default=None, alias="subTestType")
    proxy_person: Optional[StrictStr] = Field(default=None, alias="proxyPerson")
    person_in_charge: StrictStr = Field(alias="personInCharge")
    comment_ids: Optional[List[StrictInt]] = Field(default=None, alias="commentIds")
    channels: Optional[List[StrictStr]] = None
    pulse_test: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="pulseTest")
    test_facility: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="testFacility")
    report_id: Optional[StrictStr] = Field(default=None, alias="reportId")
    __properties: ClassVar[List[str]] = ["driverPosition", "customerTestRefNo", "laboratoryTestRefNo", "dateOfTest", "velocityPulse", "pulseStatus", "impactSide", "testType", "subTestType", "proxyPerson", "personInCharge", "commentIds", "channels", "pulseTest", "testFacility", "reportId"]

    @field_validator('pulse_status')
    def pulse_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['INVALID', 'PROPOSE_AS_VALID', 'VALID']):
            raise ValueError("must be one of enum values ('INVALID', 'PROPOSE_AS_VALID', 'VALID')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PreTestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PreTestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "driverPosition": obj.get("driverPosition"),
            "customerTestRefNo": obj.get("customerTestRefNo"),
            "laboratoryTestRefNo": obj.get("laboratoryTestRefNo"),
            "dateOfTest": obj.get("dateOfTest"),
            "velocityPulse": obj.get("velocityPulse"),
            "pulseStatus": obj.get("pulseStatus"),
            "impactSide": obj.get("impactSide"),
            "testType": obj.get("testType"),
            "subTestType": obj.get("subTestType"),
            "proxyPerson": obj.get("proxyPerson"),
            "personInCharge": obj.get("personInCharge"),
            "commentIds": obj.get("commentIds"),
            "channels": obj.get("channels"),
            "pulseTest": obj.get("pulseTest"),
            "testFacility": obj.get("testFacility"),
            "reportId": obj.get("reportId")
        })
        return _obj


