# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.api.server_health_api import ServerHealthApi


class TestServerHealthApi(unittest.TestCase):
    """ServerHealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerHealthApi()

    def tearDown(self) -> None:
        pass

    def test_health(self) -> None:
        """Test case for health

        Displays some general information about the server such as version and instance
        """
        pass

    def test_ping(self) -> None:
        """Test case for ping

        Simply returns 200 OK with no body
        """
        pass


if __name__ == '__main__':
    unittest.main()
