# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.api.request_api import RequestApi


class TestRequestApi(unittest.TestCase):
    """RequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RequestApi()

    def tearDown(self) -> None:
        pass

    def test_exists_project(self) -> None:
        """Test case for exists_project

        Whether a project exists
        """
        pass

    def test_exists_test(self) -> None:
        """Test case for exists_test

        Whether a test exists
        """
        pass

    def test_exists_test_series(self) -> None:
        """Test case for exists_test_series

        Whether a series exists
        """
        pass

    def test_find_project(self) -> None:
        """Test case for find_project

        Find a project
        """
        pass

    def test_find_test(self) -> None:
        """Test case for find_test

        Find a test
        """
        pass

    def test_find_test_series(self) -> None:
        """Test case for find_test_series

        Find a test series
        """
        pass

    def test_upload_data(self) -> None:
        """Test case for upload_data

        Upload test data using TestDataXML format. This function is successor from 'testdata/project/upload' , using enhanced authentication via GBSSecured.
        """
        pass


if __name__ == '__main__':
    unittest.main()
