# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.order_type import OrderType

class TestOrderType(unittest.TestCase):
    """OrderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderType:
        """Test OrderType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderType`
        """
        model = OrderType()
        if include_optional:
            return OrderType(
                path = '',
                netplan = '',
                platform = '',
                lab_netplans = '',
                creator = '',
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                target_lab_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                target_date_sample = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location = '',
                real_finish_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sample_type = '',
                build_purpose = '',
                sample = [
                    gbs3api.models.sample_data_type.SampleDataType(
                        path = '', 
                        position_number = '', 
                        sample_id = '', 
                        customer_part_number = '', 
                        amount = 56, 
                        remark = '', 
                        software = '', 
                        version = '', 
                        unloading_place = '', 
                        part_name = '', 
                        ebom = '', 
                        manufacturer = '', 
                        manufacturer_number = '', 
                        manufacturer_number_version = '', 
                        customer_version = '', 
                        warehouse_id = '', 
                        source_id = '', 
                        sample_info = gbs3api.models.sample_info_data_type.SampleInfoDataType(
                            path = '', 
                            sample_id = '', 
                            status = '', 
                            number = '', 
                            remark = '', 
                            warehouse = '', 
                            module_serieal_number = '', 
                            inflator_serieal_number = '', 
                            is_out_side = 56, 
                            location = '', 
                            responsible_person = '', 
                            checked_in_by = '', 
                            photo = [
                                gbs3api.models.image_type.ImageType(
                                    path = '', 
                                    source = '', 
                                    id_number = '', 
                                    test_object_number = '', 
                                    camery_type = '', 
                                    test_type = '', 
                                    description = '', 
                                    direction = '', 
                                    aperture = '', 
                                    exposure_time = '', 
                                    width = '', 
                                    height = '', 
                                    aspect_ratio = '', 
                                    color = '', 
                                    file_name = '', 
                                    file_data = 'YQ==', 
                                    format = '', 
                                    compression = '', 
                                    additional_group = [
                                        gbs3api.models.additional_group.AdditionalGroup(
                                            path = '', 
                                            additional = [
                                                gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                    path = '', 
                                                    key = '', 
                                                    value = '', 
                                                    report_behaviour = '', 
                                                    additional_def_mandatory = '', 
                                                    data_type = 'BOOLEAN', 
                                                    category = '', 
                                                    file_path = '', 
                                                    element_name = '', )
                                                ], 
                                            payload = gbs3api.models.payload.Payload(
                                                any = [
                                                    None
                                                    ], ), 
                                            sub_additional_group = [
                                                gbs3api.models.additional_group.AdditionalGroup(
                                                    path = '', 
                                                    additional = [
                                                        gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                            path = '', 
                                                            key = '', 
                                                            value = '', 
                                                            report_behaviour = '', 
                                                            additional_def_mandatory = '', 
                                                            data_type = 'BOOLEAN', 
                                                            category = '', 
                                                            file_path = '', 
                                                            element_name = '', )
                                                        ], 
                                                    name = '', 
                                                    type = 'PROJECT', 
                                                    category = 'MEASUREMENT_LOCATION', 
                                                    description = '', 
                                                    sort_index = 56, 
                                                    is_available = '', 
                                                    element_name = '', )
                                                ], 
                                            name = '', 
                                            type = 'PROJECT', 
                                            category = 'MEASUREMENT_LOCATION', 
                                            description = '', 
                                            sort_index = 56, 
                                            is_available = '', 
                                            element_name = '', )
                                        ], 
                                    element_name = '', )
                                ], 
                            additional_group = [
                                
                                ], 
                            element_name = '', 
                            prnumber = '', ), 
                        sample_type = gbs3api.models.sample_type_data_type.SampleTypeDataType(
                            path = '', 
                            number = '', 
                            design_drawing_number = '', 
                            element_name = '', ), 
                        location = '', 
                        is_deleted = True, 
                        prototype_sort_index = 56, 
                        sample_elements = [
                            gbs3api.models.sample_element_data_type.SampleElementDataType(
                                path = '', 
                                number = '', 
                                description = '', 
                                type = '', 
                                element_name = '', 
                                pbsbom_id = '', )
                            ], 
                        additional_group = , 
                        element_name = '', 
                        pbsfin_good_id = '', )
                    ],
                additional_group = [
                    gbs3api.models.additional_group.AdditionalGroup(
                        path = '', 
                        additional = [
                            gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                path = '', 
                                key = '', 
                                value = '', 
                                report_behaviour = '', 
                                additional_def_mandatory = '', 
                                data_type = 'BOOLEAN', 
                                category = '', 
                                file_path = '', 
                                element_name = '', )
                            ], 
                        payload = gbs3api.models.payload.Payload(
                            any = [
                                None
                                ], ), 
                        sub_additional_group = [
                            gbs3api.models.additional_group.AdditionalGroup(
                                path = '', 
                                additional = [
                                    gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                        path = '', 
                                        key = '', 
                                        value = '', 
                                        report_behaviour = '', 
                                        additional_def_mandatory = '', 
                                        data_type = 'BOOLEAN', 
                                        category = '', 
                                        file_path = '', 
                                        element_name = '', )
                                    ], 
                                name = '', 
                                type = 'PROJECT', 
                                category = 'MEASUREMENT_LOCATION', 
                                description = '', 
                                sort_index = 56, 
                                is_available = '', 
                                element_name = '', )
                            ], 
                        name = '', 
                        type = 'PROJECT', 
                        category = 'MEASUREMENT_LOCATION', 
                        description = '', 
                        sort_index = 56, 
                        is_available = '', 
                        element_name = '', )
                    ],
                element_name = '',
                pspelement = '',
                pbsid = ''
            )
        else:
            return OrderType(
                netplan = '',
        )
        """

    def testOrderType(self):
        """Test OrderType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
