# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.test_fixture import TestFixture

class TestTestFixture(unittest.TestCase):
    """TestFixture unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestFixture:
        """Test TestFixture
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestFixture`
        """
        model = TestFixture()
        if include_optional:
            return TestFixture(
                path = '',
                number = '',
                local_number = '',
                description = '',
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                scrapping_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cost_center = '',
                count = 56,
                cost = 1.337,
                release_number = '',
                test_fixture_type = gbs3api.models.test_fixture_type.TestFixtureType(
                    path = '', 
                    name = '', 
                    category = '', 
                    resource_type_scheduling = '', 
                    resource_type_scheduling_id = '', 
                    additional_group = [
                        gbs3api.models.additional_group.AdditionalGroup(
                            path = '', 
                            additional = [
                                gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                    path = '', 
                                    key = '', 
                                    value = '', 
                                    report_behaviour = '', 
                                    additional_def_mandatory = '', 
                                    data_type = 'BOOLEAN', 
                                    category = '', 
                                    file_path = '', 
                                    element_name = '', )
                                ], 
                            payload = gbs3api.models.payload.Payload(
                                any = [
                                    None
                                    ], ), 
                            sub_additional_group = [
                                gbs3api.models.additional_group.AdditionalGroup(
                                    path = '', 
                                    additional = [
                                        gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                            path = '', 
                                            key = '', 
                                            value = '', 
                                            report_behaviour = '', 
                                            additional_def_mandatory = '', 
                                            data_type = 'BOOLEAN', 
                                            category = '', 
                                            file_path = '', 
                                            element_name = '', )
                                        ], 
                                    name = '', 
                                    type = 'PROJECT', 
                                    category = 'MEASUREMENT_LOCATION', 
                                    description = '', 
                                    sort_index = 56, 
                                    is_available = '', 
                                    element_name = '', )
                                ], 
                            name = '', 
                            type = 'PROJECT', 
                            category = 'MEASUREMENT_LOCATION', 
                            description = '', 
                            sort_index = 56, 
                            is_available = '', 
                            element_name = '', )
                        ], 
                    element_name = '', ),
                company = '',
                location = '',
                contact_name = '',
                contact_phone = '',
                contact_fax = '',
                contact_email = '',
                used = 56,
                storage_position = '',
                weight = 1.337,
                resource_type_scheduling = '',
                resource_type_scheduling_id = '',
                status = 'QUARANTINE',
                sub_test_fixture = [
                    gbs3api.models.test_fixture.TestFixture(
                        path = '', 
                        number = '', 
                        local_number = '', 
                        description = '', 
                        creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        scrapping_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        cost_center = '', 
                        count = 56, 
                        cost = 1.337, 
                        release_number = '', 
                        test_fixture_type = gbs3api.models.test_fixture_type.TestFixtureType(
                            path = '', 
                            name = '', 
                            category = '', 
                            resource_type_scheduling = '', 
                            resource_type_scheduling_id = '', 
                            additional_group = [
                                gbs3api.models.additional_group.AdditionalGroup(
                                    path = '', 
                                    additional = [
                                        gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                            path = '', 
                                            key = '', 
                                            value = '', 
                                            report_behaviour = '', 
                                            additional_def_mandatory = '', 
                                            data_type = 'BOOLEAN', 
                                            category = '', 
                                            file_path = '', 
                                            element_name = '', )
                                        ], 
                                    payload = gbs3api.models.payload.Payload(
                                        any = [
                                            None
                                            ], ), 
                                    sub_additional_group = [
                                        gbs3api.models.additional_group.AdditionalGroup(
                                            path = '', 
                                            additional = [
                                                gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                    path = '', 
                                                    key = '', 
                                                    value = '', 
                                                    report_behaviour = '', 
                                                    additional_def_mandatory = '', 
                                                    data_type = 'BOOLEAN', 
                                                    category = '', 
                                                    file_path = '', 
                                                    element_name = '', )
                                                ], 
                                            name = '', 
                                            type = 'PROJECT', 
                                            category = 'MEASUREMENT_LOCATION', 
                                            description = '', 
                                            sort_index = 56, 
                                            is_available = '', 
                                            element_name = '', )
                                        ], 
                                    name = '', 
                                    type = 'PROJECT', 
                                    category = 'MEASUREMENT_LOCATION', 
                                    description = '', 
                                    sort_index = 56, 
                                    is_available = '', 
                                    element_name = '', )
                                ], 
                            element_name = '', ), 
                        company = '', 
                        location = '', 
                        contact_name = '', 
                        contact_phone = '', 
                        contact_fax = '', 
                        contact_email = '', 
                        used = 56, 
                        storage_position = '', 
                        weight = 1.337, 
                        resource_type_scheduling = '', 
                        resource_type_scheduling_id = '', 
                        status = 'QUARANTINE', 
                        additional_group = [
                            
                            ], 
                        photo = [
                            gbs3api.models.image_type.ImageType(
                                path = '', 
                                source = '', 
                                id_number = '', 
                                test_object_number = '', 
                                camery_type = '', 
                                test_type = '', 
                                description = '', 
                                direction = '', 
                                aperture = '', 
                                exposure_time = '', 
                                width = '', 
                                height = '', 
                                aspect_ratio = '', 
                                color = '', 
                                file_name = '', 
                                file_data = 'YQ==', 
                                format = '', 
                                compression = '', 
                                element_name = '', )
                            ], 
                        design_drawing = [
                            gbs3api.models.test_fixture_design_drawing.TestFixtureDesignDrawing(
                                path = '', 
                                name = '', 
                                description = '', 
                                index = '', 
                                link = '', 
                                element_name = '', )
                            ], 
                        rental = [
                            gbs3api.models.test_fixture_rental.TestFixtureRental(
                                path = '', 
                                rental_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                return_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                target_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                contact_name = '', 
                                contact_phone = '', 
                                contact_fax = '', 
                                contact_email = '', 
                                description = '', 
                                lender = '', 
                                hour_period = 56, 
                                day_period = 56, 
                                month_period = 56, 
                                indefinite_period = True, 
                                extend_loan_count = 56, 
                                element_name = '', )
                            ], 
                        status_comment = [
                            gbs3api.models.test_fixture_status_comment.TestFixtureStatusComment(
                                path = '', 
                                comment_date = '', 
                                user = '', 
                                comment = '', 
                                old_status = 'QUARANTINE', 
                                new_status = 'QUARANTINE', 
                                element_name = '', )
                            ], 
                        history_log = [
                            gbs3api.models.test_fixture_history_log.TestFixtureHistoryLog(
                                path = '', 
                                comment_date = '', 
                                user = '', 
                                comment = '', 
                                element_name = '', )
                            ], 
                        element_name = '', )
                    ],
                additional_group = [
                    gbs3api.models.additional_group.AdditionalGroup(
                        path = '', 
                        additional = [
                            gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                path = '', 
                                key = '', 
                                value = '', 
                                report_behaviour = '', 
                                additional_def_mandatory = '', 
                                data_type = 'BOOLEAN', 
                                category = '', 
                                file_path = '', 
                                element_name = '', )
                            ], 
                        payload = gbs3api.models.payload.Payload(
                            any = [
                                None
                                ], ), 
                        sub_additional_group = [
                            gbs3api.models.additional_group.AdditionalGroup(
                                path = '', 
                                additional = [
                                    gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                        path = '', 
                                        key = '', 
                                        value = '', 
                                        report_behaviour = '', 
                                        additional_def_mandatory = '', 
                                        data_type = 'BOOLEAN', 
                                        category = '', 
                                        file_path = '', 
                                        element_name = '', )
                                    ], 
                                name = '', 
                                type = 'PROJECT', 
                                category = 'MEASUREMENT_LOCATION', 
                                description = '', 
                                sort_index = 56, 
                                is_available = '', 
                                element_name = '', )
                            ], 
                        name = '', 
                        type = 'PROJECT', 
                        category = 'MEASUREMENT_LOCATION', 
                        description = '', 
                        sort_index = 56, 
                        is_available = '', 
                        element_name = '', )
                    ],
                photo = [
                    gbs3api.models.image_type.ImageType(
                        path = '', 
                        source = '', 
                        id_number = '', 
                        test_object_number = '', 
                        camery_type = '', 
                        test_type = '', 
                        description = '', 
                        direction = '', 
                        aperture = '', 
                        exposure_time = '', 
                        width = '', 
                        height = '', 
                        aspect_ratio = '', 
                        color = '', 
                        file_name = '', 
                        file_data = 'YQ==', 
                        format = '', 
                        compression = '', 
                        additional_group = [
                            gbs3api.models.additional_group.AdditionalGroup(
                                path = '', 
                                additional = [
                                    gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                        path = '', 
                                        key = '', 
                                        value = '', 
                                        report_behaviour = '', 
                                        additional_def_mandatory = '', 
                                        data_type = 'BOOLEAN', 
                                        category = '', 
                                        file_path = '', 
                                        element_name = '', )
                                    ], 
                                payload = gbs3api.models.payload.Payload(
                                    any = [
                                        None
                                        ], ), 
                                sub_additional_group = [
                                    gbs3api.models.additional_group.AdditionalGroup(
                                        path = '', 
                                        additional = [
                                            gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                path = '', 
                                                key = '', 
                                                value = '', 
                                                report_behaviour = '', 
                                                additional_def_mandatory = '', 
                                                data_type = 'BOOLEAN', 
                                                category = '', 
                                                file_path = '', 
                                                element_name = '', )
                                            ], 
                                        name = '', 
                                        type = 'PROJECT', 
                                        category = 'MEASUREMENT_LOCATION', 
                                        description = '', 
                                        sort_index = 56, 
                                        is_available = '', 
                                        element_name = '', )
                                    ], 
                                name = '', 
                                type = 'PROJECT', 
                                category = 'MEASUREMENT_LOCATION', 
                                description = '', 
                                sort_index = 56, 
                                is_available = '', 
                                element_name = '', )
                            ], 
                        element_name = '', )
                    ],
                design_drawing = [
                    gbs3api.models.test_fixture_design_drawing.TestFixtureDesignDrawing(
                        path = '', 
                        name = '', 
                        description = '', 
                        index = '', 
                        link = '', 
                        additional_group = [
                            gbs3api.models.additional_group.AdditionalGroup(
                                path = '', 
                                additional = [
                                    gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                        path = '', 
                                        key = '', 
                                        value = '', 
                                        report_behaviour = '', 
                                        additional_def_mandatory = '', 
                                        data_type = 'BOOLEAN', 
                                        category = '', 
                                        file_path = '', 
                                        element_name = '', )
                                    ], 
                                payload = gbs3api.models.payload.Payload(
                                    any = [
                                        None
                                        ], ), 
                                sub_additional_group = [
                                    gbs3api.models.additional_group.AdditionalGroup(
                                        path = '', 
                                        additional = [
                                            gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                path = '', 
                                                key = '', 
                                                value = '', 
                                                report_behaviour = '', 
                                                additional_def_mandatory = '', 
                                                data_type = 'BOOLEAN', 
                                                category = '', 
                                                file_path = '', 
                                                element_name = '', )
                                            ], 
                                        name = '', 
                                        type = 'PROJECT', 
                                        category = 'MEASUREMENT_LOCATION', 
                                        description = '', 
                                        sort_index = 56, 
                                        is_available = '', 
                                        element_name = '', )
                                    ], 
                                name = '', 
                                type = 'PROJECT', 
                                category = 'MEASUREMENT_LOCATION', 
                                description = '', 
                                sort_index = 56, 
                                is_available = '', 
                                element_name = '', )
                            ], 
                        element_name = '', )
                    ],
                rental = [
                    gbs3api.models.test_fixture_rental.TestFixtureRental(
                        path = '', 
                        rental_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        return_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        target_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        contact_name = '', 
                        contact_phone = '', 
                        contact_fax = '', 
                        contact_email = '', 
                        description = '', 
                        lender = '', 
                        hour_period = 56, 
                        day_period = 56, 
                        month_period = 56, 
                        indefinite_period = True, 
                        extend_loan_count = 56, 
                        element_name = '', )
                    ],
                status_comment = [
                    gbs3api.models.test_fixture_status_comment.TestFixtureStatusComment(
                        path = '', 
                        comment_date = '', 
                        user = '', 
                        comment = '', 
                        old_status = 'QUARANTINE', 
                        new_status = 'QUARANTINE', 
                        element_name = '', )
                    ],
                history_log = [
                    gbs3api.models.test_fixture_history_log.TestFixtureHistoryLog(
                        path = '', 
                        comment_date = '', 
                        user = '', 
                        comment = '', 
                        element_name = '', )
                    ],
                element_name = ''
            )
        else:
            return TestFixture(
                number = '',
                local_number = '',
                test_fixture_type = gbs3api.models.test_fixture_type.TestFixtureType(
                    path = '', 
                    name = '', 
                    category = '', 
                    resource_type_scheduling = '', 
                    resource_type_scheduling_id = '', 
                    additional_group = [
                        gbs3api.models.additional_group.AdditionalGroup(
                            path = '', 
                            additional = [
                                gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                    path = '', 
                                    key = '', 
                                    value = '', 
                                    report_behaviour = '', 
                                    additional_def_mandatory = '', 
                                    data_type = 'BOOLEAN', 
                                    category = '', 
                                    file_path = '', 
                                    element_name = '', )
                                ], 
                            payload = gbs3api.models.payload.Payload(
                                any = [
                                    None
                                    ], ), 
                            sub_additional_group = [
                                gbs3api.models.additional_group.AdditionalGroup(
                                    path = '', 
                                    additional = [
                                        gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                            path = '', 
                                            key = '', 
                                            value = '', 
                                            report_behaviour = '', 
                                            additional_def_mandatory = '', 
                                            data_type = 'BOOLEAN', 
                                            category = '', 
                                            file_path = '', 
                                            element_name = '', )
                                        ], 
                                    name = '', 
                                    type = 'PROJECT', 
                                    category = 'MEASUREMENT_LOCATION', 
                                    description = '', 
                                    sort_index = 56, 
                                    is_available = '', 
                                    element_name = '', )
                                ], 
                            name = '', 
                            type = 'PROJECT', 
                            category = 'MEASUREMENT_LOCATION', 
                            description = '', 
                            sort_index = 56, 
                            is_available = '', 
                            element_name = '', )
                        ], 
                    element_name = '', ),
                company = '',
                location = '',
                status = 'QUARANTINE',
        )
        """

    def testTestFixture(self):
        """Test TestFixture"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
