# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.additional_attribute_type import AdditionalAttributeType

class TestAdditionalAttributeType(unittest.TestCase):
    """AdditionalAttributeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdditionalAttributeType:
        """Test AdditionalAttributeType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdditionalAttributeType`
        """
        model = AdditionalAttributeType()
        if include_optional:
            return AdditionalAttributeType(
                path = '',
                key = '',
                value = '',
                report_behaviour = '',
                additional_def_mandatory = '',
                data_type = 'BOOLEAN',
                category = '',
                file_path = '',
                element_name = ''
            )
        else:
            return AdditionalAttributeType(
        )
        """

    def testAdditionalAttributeType(self):
        """Test AdditionalAttributeType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
