# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.validation_type import ValidationType

class TestValidationType(unittest.TestCase):
    """ValidationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationType:
        """Test ValidationType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationType`
        """
        model = ValidationType()
        if include_optional:
            return ValidationType(
                path = '',
                name = '',
                description = '',
                criterias = [
                    gbs3api.models.criteria_type.CriteriaType(
                        path = '', 
                        name = '', 
                        description = '', 
                        attribute_path = '', 
                        class_name = '', 
                        attribute = '', 
                        index = 56, 
                        message = '', 
                        message_parameters = '', 
                        active = True, 
                        element_name = '', )
                    ],
                element_name = ''
            )
        else:
            return ValidationType(
                name = '',
        )
        """

    def testValidationType(self):
        """Test ValidationType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
