# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.test_fixture_status_comment import TestFixtureStatusComment

class TestTestFixtureStatusComment(unittest.TestCase):
    """TestFixtureStatusComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestFixtureStatusComment:
        """Test TestFixtureStatusComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestFixtureStatusComment`
        """
        model = TestFixtureStatusComment()
        if include_optional:
            return TestFixtureStatusComment(
                path = '',
                comment_date = '',
                user = '',
                comment = '',
                old_status = 'QUARANTINE',
                new_status = 'QUARANTINE',
                element_name = ''
            )
        else:
            return TestFixtureStatusComment(
                comment_date = '',
                user = '',
                comment = '',
                old_status = 'QUARANTINE',
                new_status = 'QUARANTINE',
        )
        """

    def testTestFixtureStatusComment(self):
        """Test TestFixtureStatusComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
