# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.component_group_dto import ComponentGroupDto

class TestComponentGroupDto(unittest.TestCase):
    """ComponentGroupDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentGroupDto:
        """Test ComponentGroupDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentGroupDto`
        """
        model = ComponentGroupDto()
        if include_optional:
            return ComponentGroupDto(
                component_group_id = 56,
                component_group_name = '',
                component_group_label = '',
                pos_index = 56,
                part_count = 56,
                sequences = [
                    gbs3api.models.test_sequence_dto.TestSequenceDto(
                        sequence_id = 56, 
                        test_number = '', 
                        sort_index = 56, 
                        vnumber = '', 
                        test_steps = [
                            gbs3api.models.test_step_dto.TestStepDto(
                                step_id = 56, 
                                test_number = '', 
                                test_name = '', 
                                vpnr_pos = 56, 
                                requestor_name = '', 
                                requestor_phone = '', 
                                subtype_of_test = '', 
                                devices = [
                                    gbs3api.models.device_dto.DeviceDto(
                                        level = '', 
                                        resource_name = '', 
                                        equipment_name = '', 
                                        manufacturer = '', 
                                        model = '', 
                                        serial_number = '', 
                                        ident_number = '', 
                                        status = '', 
                                        calibration_date = '', 
                                        next_calibration_date = '', )
                                    ], 
                                equipment = [
                                    gbs3api.models.equipment_dto.EquipmentDto(
                                        level = '', 
                                        equipment_id = 56, 
                                        resource_name = '', 
                                        equipment_name = '', 
                                        manufacturer = '', 
                                        model = '', 
                                        serial_number = '', 
                                        ident_number = '', 
                                        status = '', 
                                        calibration_date = '', 
                                        next_calibration_date = '', )
                                    ], 
                                additional_groups = [
                                    gbs3api.models.additional_group_dto.AdditionalGroupDto(
                                        group_id = 56, 
                                        name = '', 
                                        label = '', 
                                        category = '', 
                                        sort_index = 56, 
                                        path = '', 
                                        show_in_report = '', 
                                        additionals = [
                                            gbs3api.models.additional_dto.AdditionalDto(
                                                additional_id = 56, 
                                                key = '', 
                                                value = '', 
                                                label = '', 
                                                datatype = '', 
                                                pos_index = 56, 
                                                file_path = '', 
                                                additional_category = '', 
                                                report_behaviour = '', 
                                                print_behaviour = '', 
                                                data_changed = '', )
                                            ], 
                                        child_groups = [
                                            gbs3api.models.additional_group_dto.AdditionalGroupDto(
                                                group_id = 56, 
                                                name = '', 
                                                label = '', 
                                                category = '', 
                                                sort_index = 56, 
                                                path = '', 
                                                show_in_report = '', )
                                            ], )
                                    ], )
                            ], 
                        devices = [
                            gbs3api.models.device_dto.DeviceDto(
                                level = '', 
                                resource_name = '', 
                                equipment_name = '', 
                                manufacturer = '', 
                                model = '', 
                                serial_number = '', 
                                ident_number = '', 
                                status = '', 
                                calibration_date = '', 
                                next_calibration_date = '', )
                            ], 
                        equipment = [
                            gbs3api.models.equipment_dto.EquipmentDto(
                                level = '', 
                                equipment_id = 56, 
                                resource_name = '', 
                                equipment_name = '', 
                                manufacturer = '', 
                                model = '', 
                                serial_number = '', 
                                ident_number = '', 
                                status = '', 
                                calibration_date = '', 
                                next_calibration_date = '', )
                            ], 
                        additional_groups = [
                            
                            ], )
                    ]
            )
        else:
            return ComponentGroupDto(
        )
        """

    def testComponentGroupDto(self):
        """Test ComponentGroupDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
