# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.uuc_group import UUCGroup

class TestUUCGroup(unittest.TestCase):
    """UUCGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UUCGroup:
        """Test UUCGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UUCGroup`
        """
        model = UUCGroup()
        if include_optional:
            return UUCGroup(
                path = '',
                found_in_test_series = '',
                name = '',
                model = '',
                serial_number = '',
                manufacturer = '',
                ident_nr = '',
                calibration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                next_calibration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = '',
                resource_name = '',
                element_name = ''
            )
        else:
            return UUCGroup(
        )
        """

    def testUUCGroup(self):
        """Test UUCGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
