# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.movie_type import MovieType

class TestMovieType(unittest.TestCase):
    """MovieType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MovieType:
        """Test MovieType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MovieType`
        """
        model = MovieType()
        if include_optional:
            return MovieType(
                path = '',
                id_number = '',
                origin = '',
                description = '',
                camera_id_number = '',
                camera_type = '',
                lens_id_number = '',
                lens_type = '',
                focus = '',
                lens_focal_length = '',
                number_of_images = '',
                film_speed = '',
                shutter_time = '',
                aperture = '',
                time_zero = '',
                time_vector_file_name = '',
                reference_system = '',
                location_x = '',
                location_y = '',
                location_z = '',
                theta_x = '',
                theta_y = '',
                theta_z = '',
                width_of_image = '',
                height_of_image = '',
                aspect_ratio_of_pixels = '',
                colour = '',
                name_of_movie_file = '',
                format_of_movie_file = '',
                key_frames = '',
                codec_used = '',
                compression = '',
                distortion_index = '',
                movie_images_corrected = '',
                correction_parameter_file = '',
                image_history_file_name = '',
                source = '',
                snapshots = [
                    gbs3api.models.movie_snapshot_type.MovieSnapshotType(
                        path = '', 
                        number_of_snapshots = 56, 
                        snapshot = [
                            gbs3api.models.image_type.ImageType(
                                path = '', 
                                source = '', 
                                id_number = '', 
                                test_object_number = '', 
                                camery_type = '', 
                                test_type = '', 
                                description = '', 
                                direction = '', 
                                aperture = '', 
                                exposure_time = '', 
                                width = '', 
                                height = '', 
                                aspect_ratio = '', 
                                color = '', 
                                file_name = '', 
                                file_data = 'YQ==', 
                                format = '', 
                                compression = '', 
                                additional_group = [
                                    gbs3api.models.additional_group.AdditionalGroup(
                                        path = '', 
                                        additional = [
                                            gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                path = '', 
                                                key = '', 
                                                value = '', 
                                                report_behaviour = '', 
                                                additional_def_mandatory = '', 
                                                data_type = 'BOOLEAN', 
                                                category = '', 
                                                file_path = '', 
                                                element_name = '', )
                                            ], 
                                        payload = gbs3api.models.payload.Payload(
                                            any = [
                                                None
                                                ], ), 
                                        sub_additional_group = [
                                            gbs3api.models.additional_group.AdditionalGroup(
                                                path = '', 
                                                additional = [
                                                    gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                                        path = '', 
                                                        key = '', 
                                                        value = '', 
                                                        report_behaviour = '', 
                                                        additional_def_mandatory = '', 
                                                        data_type = 'BOOLEAN', 
                                                        category = '', 
                                                        file_path = '', 
                                                        element_name = '', )
                                                    ], 
                                                name = '', 
                                                type = 'PROJECT', 
                                                category = 'MEASUREMENT_LOCATION', 
                                                description = '', 
                                                sort_index = 56, 
                                                is_available = '', 
                                                element_name = '', )
                                            ], 
                                        name = '', 
                                        type = 'PROJECT', 
                                        category = 'MEASUREMENT_LOCATION', 
                                        description = '', 
                                        sort_index = 56, 
                                        is_available = '', 
                                        element_name = '', )
                                    ], 
                                element_name = '', )
                            ], 
                        additional_group = [
                            
                            ], 
                        element_name = '', )
                    ],
                additional_group = [
                    gbs3api.models.additional_group.AdditionalGroup(
                        path = '', 
                        additional = [
                            gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                path = '', 
                                key = '', 
                                value = '', 
                                report_behaviour = '', 
                                additional_def_mandatory = '', 
                                data_type = 'BOOLEAN', 
                                category = '', 
                                file_path = '', 
                                element_name = '', )
                            ], 
                        payload = gbs3api.models.payload.Payload(
                            any = [
                                None
                                ], ), 
                        sub_additional_group = [
                            gbs3api.models.additional_group.AdditionalGroup(
                                path = '', 
                                additional = [
                                    gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                        path = '', 
                                        key = '', 
                                        value = '', 
                                        report_behaviour = '', 
                                        additional_def_mandatory = '', 
                                        data_type = 'BOOLEAN', 
                                        category = '', 
                                        file_path = '', 
                                        element_name = '', )
                                    ], 
                                name = '', 
                                type = 'PROJECT', 
                                category = 'MEASUREMENT_LOCATION', 
                                description = '', 
                                sort_index = 56, 
                                is_available = '', 
                                element_name = '', )
                            ], 
                        name = '', 
                        type = 'PROJECT', 
                        category = 'MEASUREMENT_LOCATION', 
                        description = '', 
                        sort_index = 56, 
                        is_available = '', 
                        element_name = '', )
                    ],
                element_name = ''
            )
        else:
            return MovieType(
                id_number = '',
                origin = '',
                description = '',
                camera_id_number = '',
                camera_type = '',
                lens_id_number = '',
                lens_type = '',
                focus = '',
                lens_focal_length = '',
                number_of_images = '',
                film_speed = '',
                shutter_time = '',
                aperture = '',
                time_zero = '',
                time_vector_file_name = '',
                reference_system = '',
                location_x = '',
                location_y = '',
                location_z = '',
                theta_x = '',
                theta_y = '',
                theta_z = '',
                width_of_image = '',
                height_of_image = '',
                aspect_ratio_of_pixels = '',
                colour = '',
                name_of_movie_file = '',
                format_of_movie_file = '',
                key_frames = '',
                codec_used = '',
                compression = '',
                distortion_index = '',
                movie_images_corrected = '',
                correction_parameter_file = '',
                image_history_file_name = '',
        )
        """

    def testMovieType(self):
        """Test MovieType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
