# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.resource_type_dto import ResourceTypeDto

class TestResourceTypeDto(unittest.TestCase):
    """ResourceTypeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceTypeDto:
        """Test ResourceTypeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceTypeDto`
        """
        model = ResourceTypeDto()
        if include_optional:
            return ResourceTypeDto(
                id = 56,
                data_id = 56,
                class_name = '',
                name = '',
                schedule_types = [
                    56
                    ],
                resources = [
                    56
                    ]
            )
        else:
            return ResourceTypeDto(
        )
        """

    def testResourceTypeDto(self):
        """Test ResourceTypeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
