# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.sample_element_data_type import SampleElementDataType

class TestSampleElementDataType(unittest.TestCase):
    """SampleElementDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleElementDataType:
        """Test SampleElementDataType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleElementDataType`
        """
        model = SampleElementDataType()
        if include_optional:
            return SampleElementDataType(
                path = '',
                number = '',
                description = '',
                type = '',
                additional_group = gbs3api.models.additional_group.AdditionalGroup(
                    path = '', 
                    additional = [
                        gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                            path = '', 
                            key = '', 
                            value = '', 
                            report_behaviour = '', 
                            additional_def_mandatory = '', 
                            data_type = 'BOOLEAN', 
                            category = '', 
                            file_path = '', 
                            element_name = '', )
                        ], 
                    payload = gbs3api.models.payload.Payload(
                        any = [
                            None
                            ], ), 
                    sub_additional_group = [
                        gbs3api.models.additional_group.AdditionalGroup(
                            path = '', 
                            additional = [
                                gbs3api.models.additional_attribute_type.AdditionalAttributeType(
                                    path = '', 
                                    key = '', 
                                    value = '', 
                                    report_behaviour = '', 
                                    additional_def_mandatory = '', 
                                    data_type = 'BOOLEAN', 
                                    category = '', 
                                    file_path = '', 
                                    element_name = '', )
                                ], 
                            name = '', 
                            type = 'PROJECT', 
                            category = 'MEASUREMENT_LOCATION', 
                            description = '', 
                            sort_index = 56, 
                            is_available = '', 
                            element_name = '', )
                        ], 
                    name = '', 
                    type = 'PROJECT', 
                    category = 'MEASUREMENT_LOCATION', 
                    description = '', 
                    sort_index = 56, 
                    is_available = '', 
                    element_name = '', ),
                element_name = '',
                pbsbom_id = ''
            )
        else:
            return SampleElementDataType(
                number = '',
        )
        """

    def testSampleElementDataType(self):
        """Test SampleElementDataType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
