# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.test_step_details_dto import TestStepDetailsDTO

class TestTestStepDetailsDTO(unittest.TestCase):
    """TestStepDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestStepDetailsDTO:
        """Test TestStepDetailsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestStepDetailsDTO`
        """
        model = TestStepDetailsDTO()
        if include_optional:
            return TestStepDetailsDTO(
                test_series_id = 56,
                schedule_parent = 56,
                schedule_data_id = 56,
                label = '',
                info = '',
                begin = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                part_count = 56,
                sched_status = '',
                resource_name = '',
                class_name = '',
                resource_category = '',
                schedule_type = ''
            )
        else:
            return TestStepDetailsDTO(
        )
        """

    def testTestStepDetailsDTO(self):
        """Test TestStepDetailsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
