# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.person_dto import PersonDto

class TestPersonDto(unittest.TestCase):
    """PersonDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonDto:
        """Test PersonDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonDto`
        """
        model = PersonDto()
        if include_optional:
            return PersonDto(
                person_id = 56,
                last_name = '',
                first_name = '',
                email = '',
                user = '',
                task_def = 56,
                phone_number = '',
                fax_number = '',
                categories = '',
                is_scheduling_manpower = True,
                enum_value = 56,
                job_title = '',
                company = ''
            )
        else:
            return PersonDto(
        )
        """

    def testPersonDto(self):
        """Test PersonDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
