# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.component_test_group_type import ComponentTestGroupType

class TestComponentTestGroupType(unittest.TestCase):
    """ComponentTestGroupType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentTestGroupType:
        """Test ComponentTestGroupType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentTestGroupType`
        """
        model = ComponentTestGroupType()
        if include_optional:
            return ComponentTestGroupType(
                path = '',
                name = '',
                description = '',
                position = 56,
                element_name = ''
            )
        else:
            return ComponentTestGroupType(
                name = '',
        )
        """

    def testComponentTestGroupType(self):
        """Test ComponentTestGroupType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
