# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.7.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs3api.models.bom_dto import BomDto

class TestBomDto(unittest.TestCase):
    """BomDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BomDto:
        """Test BomDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BomDto`
        """
        model = BomDto()
        if include_optional:
            return BomDto(
                bom_id = 56,
                material = '',
                material_description = '',
                plant = '',
                item_number = '',
                item_category = '',
                source_system_key = '',
                bom_elements = [
                    gbs3api.models.bom_dto.BomDto(
                        bom_id = 56, 
                        material = '', 
                        material_description = '', 
                        plant = '', 
                        item_number = '', 
                        item_category = '', 
                        source_system_key = '', 
                        bom_elements = [
                            gbs3api.models.bom_dto.BomDto(
                                bom_id = 56, 
                                material = '', 
                                material_description = '', 
                                plant = '', 
                                item_number = '', 
                                item_category = '', 
                                source_system_key = '', )
                            ], )
                    ]
            )
        else:
            return BomDto(
        )
        """

    def testBomDto(self):
        """Test BomDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
