# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.models.channel_dto import ChannelDto

class TestChannelDto(unittest.TestCase):
    """ChannelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelDto:
        """Test ChannelDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelDto`
        """
        model = ChannelDto()
        if include_optional:
            return ChannelDto(
                iso_code = ''
            )
        else:
            return ChannelDto(
                iso_code = '',
        )
        """

    def testChannelDto(self):
        """Test ChannelDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
