# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.models.filter_field_metadata_dto import FilterFieldMetadataDto

class TestFilterFieldMetadataDto(unittest.TestCase):
    """FilterFieldMetadataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilterFieldMetadataDto:
        """Test FilterFieldMetadataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilterFieldMetadataDto`
        """
        model = FilterFieldMetadataDto()
        if include_optional:
            return FilterFieldMetadataDto(
                var_field = '',
                label = '',
                description = '',
                data_type = '',
                nullable = True,
                constraints = {
                    'key' : null
                    },
                allowed_values = gbs4api.models.filter_metadata_allowed_values_dto.FilterMetadataAllowedValuesDto(
                    mode = 'INLINE', 
                    values = [
                        gbs4api.models.filter_metadata_allowed_value_dto.FilterMetadataAllowedValueDto(
                            value = '', 
                            label = '', )
                        ], 
                    endpoint = gbs4api.models.filter_metadata_endpoint_source_dto.FilterMetadataEndpointSourceDto(
                        method = '', 
                        url = '', 
                        value_field = '', 
                        label_field = '', 
                        label_template = '', ), ),
                deprecated = True
            )
        else:
            return FilterFieldMetadataDto(
        )
        """

    def testFilterFieldMetadataDto(self):
        """Test FilterFieldMetadataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
