# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.api.test_facility_controller_api import TestFacilityControllerApi


class TestTestFacilityControllerApi(unittest.TestCase):
    """TestFacilityControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestFacilityControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_test_facility(self) -> None:
        """Test case for create_test_facility

        """
        pass

    def test_delete_test_facility(self) -> None:
        """Test case for delete_test_facility

        """
        pass

    def test_get_test_facilities(self) -> None:
        """Test case for get_test_facilities

        """
        pass

    def test_get_test_facility(self) -> None:
        """Test case for get_test_facility

        """
        pass

    def test_update_test_facility(self) -> None:
        """Test case for update_test_facility

        """
        pass


if __name__ == '__main__':
    unittest.main()
