# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.api.file_controller_api import FileControllerApi


class TestFileControllerApi(unittest.TestCase):
    """FileControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        Download a file
        """
        pass


if __name__ == '__main__':
    unittest.main()
