# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.models.parameter_value_dto import ParameterValueDto

class TestParameterValueDto(unittest.TestCase):
    """ParameterValueDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParameterValueDto:
        """Test ParameterValueDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParameterValueDto`
        """
        model = ParameterValueDto()
        if include_optional:
            return ParameterValueDto(
                value = '',
                pretest_customer_ref = '',
                parameter_name = '',
                value_list_name = ''
            )
        else:
            return ParameterValueDto(
                pretest_customer_ref = '',
                parameter_name = '',
        )
        """

    def testParameterValueDto(self):
        """Test ParameterValueDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
