# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.models.pulse_test_dto import PulseTestDto

class TestPulseTestDto(unittest.TestCase):
    """PulseTestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PulseTestDto:
        """Test PulseTestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PulseTestDto`
        """
        model = PulseTestDto()
        if include_optional:
            return PulseTestDto(
                driver_position = 56,
                customer_test_ref_no = '',
                laboratory_test_ref_no = '0',
                date_of_test = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = 'INVALID',
                impact_side = '',
                test_type = '',
                sub_test_type = '',
                proxy_person = '',
                person_in_charge = '',
                comment_ids = [
                    56
                    ],
                channels = [
                    ''
                    ],
                external_test_id = '0',
                pre_tests = [
                    ''
                    ],
                velocity = 1.337,
                report_id = ''
            )
        else:
            return PulseTestDto(
                driver_position = 56,
                customer_test_ref_no = '',
                laboratory_test_ref_no = '0',
                date_of_test = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = 'INVALID',
                person_in_charge = '',
                external_test_id = '0',
        )
        """

    def testPulseTestDto(self):
        """Test PulseTestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
