# coding: utf-8

"""
    GBS 4 API

    Global Backbone System Version 4 API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gbs4api.models.parameter_def_dto import ParameterDefDto

class TestParameterDefDto(unittest.TestCase):
    """ParameterDefDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParameterDefDto:
        """Test ParameterDefDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParameterDefDto`
        """
        model = ParameterDefDto()
        if include_optional:
            return ParameterDefDto(
                name = '',
                sort_index = 56,
                value_list_name = '',
                test_facility_name = '',
                deprecated = True
            )
        else:
            return ParameterDefDto(
                name = '',
                sort_index = 56,
                test_facility_name = '',
        )
        """

    def testParameterDefDto(self):
        """Test ParameterDefDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
