# coding: utf-8

"""
    GBS API

    All REST API endpoints for GBS

    The version of the OpenAPI document: 1.8.0
    Contact: gbs-support@trw1.onmicrosoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from gbs3api.models.history_log import HistoryLog

from gbs3api.api_client import ApiClient, RequestSerialized
from gbs3api.api_response import ApiResponse
from gbs3api.rest import RESTResponseType


class HistoryApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_logs(
        self,
        var_from: Annotated[Optional[StrictStr], Field(description="The from date to query; Formatted as yyyy-MM-ddTHH:mm:ss.SSSZ")] = None,
        to: Annotated[Optional[StrictStr], Field(description="The to date to query; yyyy-MM-ddTHH:mm:ss.SSSZ")] = None,
        entity_id: Annotated[Optional[StrictInt], Field(description="Cannot be used together with objectType! The id of the entity to filter by")] = None,
        object_type: Annotated[Optional[StrictStr], Field(description="Cannot be used together with entityId! The type of object to filter by")] = None,
        user: Annotated[Optional[StrictStr], Field(description="The user to filter by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[HistoryLog]:
        """Get history log entries through different query parameters


        :param var_from: The from date to query; Formatted as yyyy-MM-ddTHH:mm:ss.SSSZ
        :type var_from: str
        :param to: The to date to query; yyyy-MM-ddTHH:mm:ss.SSSZ
        :type to: str
        :param entity_id: Cannot be used together with objectType! The id of the entity to filter by
        :type entity_id: int
        :param object_type: Cannot be used together with entityId! The type of object to filter by
        :type object_type: str
        :param user: The user to filter by
        :type user: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_logs_serialize(
            var_from=var_from,
            to=to,
            entity_id=entity_id,
            object_type=object_type,
            user=user,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HistoryLog]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_logs_with_http_info(
        self,
        var_from: Annotated[Optional[StrictStr], Field(description="The from date to query; Formatted as yyyy-MM-ddTHH:mm:ss.SSSZ")] = None,
        to: Annotated[Optional[StrictStr], Field(description="The to date to query; yyyy-MM-ddTHH:mm:ss.SSSZ")] = None,
        entity_id: Annotated[Optional[StrictInt], Field(description="Cannot be used together with objectType! The id of the entity to filter by")] = None,
        object_type: Annotated[Optional[StrictStr], Field(description="Cannot be used together with entityId! The type of object to filter by")] = None,
        user: Annotated[Optional[StrictStr], Field(description="The user to filter by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[HistoryLog]]:
        """Get history log entries through different query parameters


        :param var_from: The from date to query; Formatted as yyyy-MM-ddTHH:mm:ss.SSSZ
        :type var_from: str
        :param to: The to date to query; yyyy-MM-ddTHH:mm:ss.SSSZ
        :type to: str
        :param entity_id: Cannot be used together with objectType! The id of the entity to filter by
        :type entity_id: int
        :param object_type: Cannot be used together with entityId! The type of object to filter by
        :type object_type: str
        :param user: The user to filter by
        :type user: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_logs_serialize(
            var_from=var_from,
            to=to,
            entity_id=entity_id,
            object_type=object_type,
            user=user,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HistoryLog]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_logs_without_preload_content(
        self,
        var_from: Annotated[Optional[StrictStr], Field(description="The from date to query; Formatted as yyyy-MM-ddTHH:mm:ss.SSSZ")] = None,
        to: Annotated[Optional[StrictStr], Field(description="The to date to query; yyyy-MM-ddTHH:mm:ss.SSSZ")] = None,
        entity_id: Annotated[Optional[StrictInt], Field(description="Cannot be used together with objectType! The id of the entity to filter by")] = None,
        object_type: Annotated[Optional[StrictStr], Field(description="Cannot be used together with entityId! The type of object to filter by")] = None,
        user: Annotated[Optional[StrictStr], Field(description="The user to filter by")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get history log entries through different query parameters


        :param var_from: The from date to query; Formatted as yyyy-MM-ddTHH:mm:ss.SSSZ
        :type var_from: str
        :param to: The to date to query; yyyy-MM-ddTHH:mm:ss.SSSZ
        :type to: str
        :param entity_id: Cannot be used together with objectType! The id of the entity to filter by
        :type entity_id: int
        :param object_type: Cannot be used together with entityId! The type of object to filter by
        :type object_type: str
        :param user: The user to filter by
        :type user: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_logs_serialize(
            var_from=var_from,
            to=to,
            entity_id=entity_id,
            object_type=object_type,
            user=user,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HistoryLog]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_logs_serialize(
        self,
        var_from,
        to,
        entity_id,
        object_type,
        user,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if entity_id is not None:
            
            _query_params.append(('entity-id', entity_id))
            
        if object_type is not None:
            
            _query_params.append(('object-type', object_type))
            
        if user is not None:
            
            _query_params.append(('user', user))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyV1', 
            'CredentialsParameter', 
            'BasicAuth', 
            'JWTCookie', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/webservice/history/logs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


